# Generated by Django 5.2.1 on 2025-08-01 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_tipodocumento_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educaciondocente',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveleducativo'),
        ),
    ]
