# Generated by Django 5.2.1 on 2025-08-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_educaciondocente_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='niveleducativo',
            name='categoria',
            field=models.CharField(choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria'), ('secundaria', 'Secundaria'), ('media', 'Media'), ('superior', 'Superior')], default='primaria', max_length=30),
        ),
    ]
