# Generated by Django 5.2 on 2025-08-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_niveleducativo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciadocente',
            name='documento_soporte',
        ),
        migrations.AlterField(
            model_name='experienciadocente',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='experienciadocente',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
