# Generated by Django 5.2.1 on 2025-10-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_experienciadocente_documento_soporte_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignaturaEstudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='core.asignatura')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_inscritas', to='core.perfildeusuario')),
            ],
            options={
                'verbose_name': 'Asignatura de Estudiante',
                'verbose_name_plural': 'Asignaturas de Estudiantes',
                'unique_together': {('estudiante', 'asignatura')},
            },
        ),
        migrations.AddField(
            model_name='perfildeusuario',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='perfiles_estudiantes', through='core.AsignaturaEstudiante', to='core.asignatura'),
        ),
    ]
